### ISSUE TITLE
Default size factor is not 1:1

### ISSUE THREAD

**Issue by zirafa** [mtl/svg2mod#17]
I've drawn an SVG to scale in Inkscape (90 DPI), but when importing into KiCad the result is not 1:1 (1mm in Inkscape = 1mm in KiCad), the output is actually slightly larger. It ends up being something like 1:1.06665.

To correct for this, I have to use -f .93751464867 to my svg2mod command. Am I missing something obvious, or is this a bug?

**Comment by EsserPrototyping** [comment]
I also realized that problem. I´m not very familiar with phyton, but maybe this has to do with the svg-parser.  It would be great if somebody can clarify this.. the script itself is super useful!

**Comment by Tom-Archer** [comment]
Same issue here, thanks for the scaling factor @zirafa - I might have a poke around the svg-parser to see if there's anything obvious.

**Comment by Tom-Archer** [comment]
Ok, so I think I've found the issue. At several places in [svg2mod.py](https://github.com/mtl/svg2mod/blob/master/svg2mod/svg2mod.py) it makes reference to the Inkscape DPI being 90. However it seems that in [Inkscape 0.92](http://wiki.inkscape.org/wiki/index.php/Release_notes/0.92#Important_changes) the default document resolution was changed from 90 to 96. As it turns out, 90/96 = 0.9375 which is pretty much spot on the scaling factor @zirafa stated.

**Comment by mtl** [comment]
Should be fixed in 0b7103b212a26fddc344418daacf961ae14c448a. Thanks, all.
